if (TARGET Clover::Core)
    return()
endif ()

if (CMAKE_VERSION VERSION_LESS 3.19)
    message(FATAL_ERROR "CloverCore: CMake >= 3.19 required.")
endif ()

if (WIN32)
    set(_cc_sys "windows")
    set(_cc_sysmacro CloverNT_SYSTEM_WINDOWS)
elseif (UNIX AND NOT APPLE)
    set(_cc_sys "linux")
    set(_cc_sysmacro CloverNT_SYSTEM_LINUX)
else ()
    message(FATAL_ERROR "CloverCore: only windows/linux runtimes are published.")
endif ()

if (NOT CLOVER_CORE_ARCH)
    if (CMAKE_SYSTEM_PROCESSOR MATCHES "[Aa][Rr][Mm]64|aarch64")
        set(CLOVER_CORE_ARCH "arm64")
    elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64|amd64|x64")
        set(CLOVER_CORE_ARCH "x64")
    elseif (CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(CLOVER_CORE_ARCH "x64")
    else ()
        message(FATAL_ERROR "CloverCore: cannot infer arch from '${CMAKE_SYSTEM_PROCESSOR}'; set CLOVER_CORE_ARCH.")
    endif ()
endif ()
if (CLOVER_CORE_ARCH STREQUAL "arm64")
    set(_cc_archmacro CloverNT_ARCH_ARM64)
else ()
    set(_cc_archmacro CloverNT_ARCH_X64)
endif ()
set(_cc_slot "${_cc_sys}-${CLOVER_CORE_ARCH}")

if (WIN32)
    set(_cc_libname "CloverCore.lib")
else ()
    set(_cc_libname "libCloverCore.so")
endif ()

set(_cc_lib "")
if (CLOVER_CORE_LIB)
    set(_cc_lib "${CLOVER_CORE_LIB}")
    if (NOT EXISTS "${_cc_lib}")
        message(FATAL_ERROR "CloverCore: CLOVER_CORE_LIB does not exist: ${_cc_lib}")
    endif ()
else ()
    if (CLOVER_CORE_SDK_DIR)
        get_filename_component(_cc_root "${CLOVER_CORE_SDK_DIR}" ABSOLUTE)
    else ()
        get_filename_component(_cc_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
    endif ()
    foreach (_cand
            "${_cc_root}/lib/${_cc_slot}/${_cc_libname}"
            "${_cc_root}/lib/${_cc_libname}")
        if (EXISTS "${_cand}")
            set(_cc_lib "${_cand}")
            break()
        endif ()
    endforeach ()
    if (NOT _cc_lib)
        message(FATAL_ERROR
                "CloverCore: no ${_cc_libname} for slot '${_cc_slot}' under '${_cc_root}/lib'.\n"
                "The CloverAPI checkout should ship the import library. Point CLOVER_CORE_SDK_DIR at the "
                "SDK root, or set CLOVER_CORE_LIB to the library path.")
    endif ()
endif ()
message(STATUS "CloverCore: using import lib ${_cc_lib}")

if (NOT CLOVER_CORE_INCLUDE_DIR)
    get_filename_component(_cc_inc "${CMAKE_CURRENT_LIST_DIR}/../include" ABSOLUTE)
    if (EXISTS "${_cc_inc}/CloverNT")
        set(CLOVER_CORE_INCLUDE_DIR "${_cc_inc}")
    endif ()
endif ()
if (NOT CLOVER_CORE_INCLUDE_DIR)
    message(FATAL_ERROR
            "CloverCore: CLOVER_CORE_INCLUDE_DIR is unset and could not be derived from the SDK layout.")
endif ()

add_library(Clover::Core SHARED IMPORTED GLOBAL)
if (WIN32)
    set_target_properties(Clover::Core PROPERTIES IMPORTED_IMPLIB "${_cc_lib}")
else ()
    set_target_properties(Clover::Core PROPERTIES IMPORTED_LOCATION "${_cc_lib}")
endif ()
set_target_properties(Clover::Core PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${CLOVER_CORE_INCLUDE_DIR}"
        INTERFACE_COMPILE_DEFINITIONS "${_cc_sysmacro};${_cc_archmacro}")
if (WIN32)
    set_property(TARGET Clover::Core APPEND PROPERTY INTERFACE_COMPILE_DEFINITIONS WIN32_LEAN_AND_MEAN NOMINMAX)
endif ()
