if (TARGET Clover::Core)
    return()
endif ()

if (CMAKE_VERSION VERSION_LESS 3.19)
    message(FATAL_ERROR "clover-core: CMake >= 3.19 required (string(JSON), file(ARCHIVE_EXTRACT)).")
endif ()

if (NOT DEFINED CLOVER_CORE_REPO)
    set(CLOVER_CORE_REPO "CloverNT/CloverCore")
endif ()
if (NOT DEFINED CLOVER_CORE_VERSION)
    set(CLOVER_CORE_VERSION "latest")
endif ()
if (NOT DEFINED CLOVER_CORE_OFFLINE)
    set(CLOVER_CORE_OFFLINE OFF)
endif ()
if (NOT DEFINED CLOVER_CORE_UPDATE)
    set(CLOVER_CORE_UPDATE OFF)
endif ()

if (WIN32)
    set(_cc_sys "windows")
    set(_cc_sysmacro CloverNT_SYSTEM_WINDOWS)
elseif (UNIX AND NOT APPLE)
    set(_cc_sys "linux")
    set(_cc_sysmacro CloverNT_SYSTEM_LINUX)
else ()
    message(FATAL_ERROR "clover-core: only windows/linux runtimes are published.")
endif ()

if (NOT CLOVER_CORE_ARCH)
    if (CMAKE_SYSTEM_PROCESSOR MATCHES "[Aa][Rr][Mm]64|aarch64")
        set(CLOVER_CORE_ARCH "arm64")
    elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64|amd64|x64")
        set(CLOVER_CORE_ARCH "x64")
    elseif (CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(CLOVER_CORE_ARCH "x64")
    else ()
        message(FATAL_ERROR "clover-core: cannot infer arch from '${CMAKE_SYSTEM_PROCESSOR}'; set CLOVER_CORE_ARCH.")
    endif ()
endif ()
if (CLOVER_CORE_ARCH STREQUAL "arm64")
    set(_cc_archmacro CloverNT_ARCH_ARM64)
else ()
    set(_cc_archmacro CloverNT_ARCH_X64)
endif ()
set(_cc_slot "${_cc_sys}-${CLOVER_CORE_ARCH}")

if (WIN32)
    set(_cc_libname "CloverCore.lib")
else ()
    set(_cc_libname "libCloverCore.so")
endif ()

set(_cc_lib "")

if (CLOVER_CORE_LIB)
    set(_cc_lib "${CLOVER_CORE_LIB}")
    if (NOT EXISTS "${_cc_lib}")
        message(FATAL_ERROR "clover-core: CLOVER_CORE_LIB does not exist: ${_cc_lib}")
    endif ()
    message(STATUS "clover-core: using local import lib ${_cc_lib}")
else ()
    # cache dir
    if (NOT CLOVER_CORE_CACHE_DIR)
        if (DEFINED ENV{CLOVER_CORE_CACHE_DIR})
            set(CLOVER_CORE_CACHE_DIR "$ENV{CLOVER_CORE_CACHE_DIR}")
        elseif (WIN32 AND DEFINED ENV{LOCALAPPDATA})
            set(CLOVER_CORE_CACHE_DIR "$ENV{LOCALAPPDATA}/clover-core")
        elseif (DEFINED ENV{XDG_CACHE_HOME})
            set(CLOVER_CORE_CACHE_DIR "$ENV{XDG_CACHE_HOME}/clover-core")
        elseif (DEFINED ENV{HOME})
            set(CLOVER_CORE_CACHE_DIR "$ENV{HOME}/.cache/clover-core")
        else ()
            set(CLOVER_CORE_CACHE_DIR "${CMAKE_BINARY_DIR}/clover-core")
        endif ()
    endif ()
    file(MAKE_DIRECTORY "${CLOVER_CORE_CACHE_DIR}")

    set(_cc_hdr "Accept: application/vnd.github+json")
    if (CLOVER_CORE_GITHUB_TOKEN)
        set(_cc_auth "Authorization: Bearer ${CLOVER_CORE_GITHUB_TOKEN}")
    else ()
        set(_cc_auth "X-CloverCore-NoAuth: 1")
    endif ()

    set(_cc_req "${CLOVER_CORE_VERSION}:${_cc_slot}")
    set(_cc_dir "")
    if (NOT CLOVER_CORE_UPDATE
            AND DEFINED CLOVER_CORE_CACHED_DIR
            AND CLOVER_CORE_CACHED_REQ STREQUAL "${_cc_req}"
            AND EXISTS "${CLOVER_CORE_CACHED_DIR}/.clover-core-ok")
        set(_cc_dir "${CLOVER_CORE_CACHED_DIR}")
        message(STATUS "clover-core: using cached ${_cc_dir}")
    endif ()

    if (NOT _cc_dir)
        if (CLOVER_CORE_OFFLINE)
            file(GLOB _cc_cands "${CLOVER_CORE_CACHE_DIR}/clover-core-*-${_cc_slot}")
            list(SORT _cc_cands)
            list(REVERSE _cc_cands)
            foreach (_c ${_cc_cands})
                if (IS_DIRECTORY "${_c}" AND EXISTS "${_c}/.clover-core-ok")
                    set(_cc_dir "${_c}")
                    break()
                endif ()
            endforeach ()
            if (NOT _cc_dir)
                message(FATAL_ERROR "clover-core: OFFLINE and no cached ${_cc_slot} package in ${CLOVER_CORE_CACHE_DIR}.")
            endif ()
            message(STATUS "clover-core: OFFLINE, using cached ${_cc_dir}")
        else ()
            if (CLOVER_CORE_VERSION STREQUAL "latest")
                set(_cc_api "https://api.github.com/repos/${CLOVER_CORE_REPO}/releases/latest")
            else ()
                set(_cc_api "https://api.github.com/repos/${CLOVER_CORE_REPO}/releases/tags/${CLOVER_CORE_VERSION}")
            endif ()

            set(_cc_json "${CLOVER_CORE_CACHE_DIR}/.release-${CLOVER_CORE_VERSION}-${_cc_slot}.json")
            message(STATUS "clover-core: querying ${_cc_api}")
            file(DOWNLOAD "${_cc_api}" "${_cc_json}"
                    HTTPHEADER "${_cc_hdr}" HTTPHEADER "${_cc_auth}" TLS_VERIFY ON STATUS _cc_st)
            list(GET _cc_st 0 _cc_rc)
            if (NOT _cc_rc EQUAL 0)
                list(GET _cc_st 1 _cc_msg)
                message(FATAL_ERROR "clover-core: release query failed (${_cc_msg}). URL: ${_cc_api}")
            endif ()

            file(READ "${_cc_json}" _cc_body)
            string(JSON _cc_n ERROR_VARIABLE _cc_jerr LENGTH "${_cc_body}" assets)
            if (_cc_jerr OR NOT _cc_n)
                message(FATAL_ERROR "clover-core: no assets in release JSON (${_cc_jerr}).")
            endif ()
            set(_cc_name "")
            set(_cc_url "")
            math(EXPR _cc_last "${_cc_n} - 1")
            foreach (_i RANGE 0 ${_cc_last})
                string(JSON _cc_a GET "${_cc_body}" assets ${_i})
                string(JSON _cc_an GET "${_cc_a}" name)
                if (_cc_an MATCHES "^clover-core-.*-${_cc_slot}\\.zip$")
                    string(JSON _cc_url GET "${_cc_a}" browser_download_url)
                    set(_cc_name "${_cc_an}")
                    break()
                endif ()
            endforeach ()
            if (NOT _cc_name)
                message(FATAL_ERROR "clover-core: no clover-core-*-${_cc_slot}.zip asset in ${_cc_api}.")
            endif ()

            string(REGEX REPLACE "\\.zip$" "" _cc_stem "${_cc_name}")
            set(_cc_dir "${CLOVER_CORE_CACHE_DIR}/${_cc_stem}")
            set(_cc_zip "${CLOVER_CORE_CACHE_DIR}/${_cc_name}")

            if (EXISTS "${_cc_dir}/.clover-core-ok")
                message(STATUS "clover-core: already cached ${_cc_stem}")
            else ()
                if (NOT EXISTS "${_cc_zip}")
                    message(STATUS "clover-core: downloading ${_cc_name}")
                    file(DOWNLOAD "${_cc_url}" "${_cc_zip}.part"
                            HTTPHEADER "${_cc_auth}" TLS_VERIFY ON SHOW_PROGRESS STATUS _cc_dst)
                    list(GET _cc_dst 0 _cc_drc)
                    if (NOT _cc_drc EQUAL 0)
                        file(REMOVE "${_cc_zip}.part")
                        list(GET _cc_dst 1 _cc_dmsg)
                        message(FATAL_ERROR "clover-core: download failed (${_cc_dmsg}). URL: ${_cc_url}")
                    endif ()
                    file(RENAME "${_cc_zip}.part" "${_cc_zip}")
                endif ()
                message(STATUS "clover-core: extracting ${_cc_name}")
                file(REMOVE_RECURSE "${_cc_dir}")
                file(ARCHIVE_EXTRACT INPUT "${_cc_zip}" DESTINATION "${CLOVER_CORE_CACHE_DIR}")
                if (NOT EXISTS "${_cc_dir}/${_cc_libname}")
                    message(FATAL_ERROR "clover-core: extracted package missing ${_cc_libname} (${_cc_dir}).")
                endif ()
                file(WRITE "${_cc_dir}/.clover-core-ok" "${_cc_name}\n")
            endif ()
        endif ()

        set(CLOVER_CORE_CACHED_DIR "${_cc_dir}" CACHE INTERNAL "resolved CloverCore package dir")
        set(CLOVER_CORE_CACHED_REQ "${_cc_req}" CACHE INTERNAL "resolved CloverCore request key")
    endif ()

    set(_cc_lib "${_cc_dir}/${_cc_libname}")
    if (NOT EXISTS "${_cc_lib}")
        message(FATAL_ERROR "clover-core: import library missing at ${_cc_lib}.")
    endif ()
endif ()

add_library(Clover::Core SHARED IMPORTED GLOBAL)
if (WIN32)
    set_target_properties(Clover::Core PROPERTIES IMPORTED_IMPLIB "${_cc_lib}")
else ()
    set_target_properties(Clover::Core PROPERTIES IMPORTED_LOCATION "${_cc_lib}")
endif ()

if (NOT CLOVER_CORE_INCLUDE_DIR)
    message(FATAL_ERROR
            "clover-core: CLOVER_CORE_INCLUDE_DIR is unset. The CloverAPI package sets it; "
            "set it yourself only if you include(clover-core) standalone.")
endif ()
set_target_properties(Clover::Core PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${CLOVER_CORE_INCLUDE_DIR}"
        INTERFACE_COMPILE_DEFINITIONS "${_cc_sysmacro};${_cc_archmacro}")
if (WIN32)
    set_property(TARGET Clover::Core APPEND PROPERTY INTERFACE_COMPILE_DEFINITIONS WIN32_LEAN_AND_MEAN NOMINMAX)
endif ()
